
# .swiftlint.yml
excluded: # paths to ignore during linting
  - Sources/Persistence/Apollo

# Rule Configuration
line_length: 120
type_body_length:
  - 300 # warning
  - 400 # error
function_body_length:
  - 40 # warning
  - 50 # error
file_length:
  warning: 500
  error: 800
cyclomatic_complexity:
  warning: 10
  error: 15
type_name:
  min_length: 3 # warning
  max_length: # warning and error
    warning: 40
    error: 50
identifier_name:
  min_length: # warning and error
    error: 3
  excluded: # excluded from min_length
    - id
    - to
    - at
    - by
    - of
    - on
    - in
    - or
    - up
    - as
    - is
    - if
    - rx
    - vm
force_unwrapping: warning # implicitly unwrapped optionals
force_try:
  severity: warning # force tries
force_cast: warning # force casts
large_tuple:
  warning: 3
  error: 4

# Disabled Rules
disabled_rules:
  - todo
  - trailing_whitespace
  - trailing_comma
  - multiple_closures_with_trailing_closure

# Opt-In Rules
opt_in_rules:
  - empty_count
  - closure_spacing
  - collection_alignment
  - array_init
  - contains_over_first_not_nil
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - no_extension_access_modifier
  - optional_enum_case_matching
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - vertical_whitespace_closing_braces