name: Swift CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'  # Especifica la versión de Xcode que deseas usar

      - name: Install dependencies
        run: |
          cd Persistence
          swift package resolve

      - name: Build package
        run: |
          cd Persistence
          swift build

      - name: Run tests
        run: |
          cd Persistence
          swift test
